#!/usr/bin/env python3
"""Assemble a credit risk assessment report from results artifacts.

Reads CSVs and PNGs from results/ and generates a DOCX report.
Requires python-docx.

Usage:
  python scripts/generate_report.py
  python scripts/generate_report.py --output report/my_report.docx
"""
import argparse
import sys
from pathlib import Path

RESULTS = Path(__file__).resolve().parent.parent / "results"
REPORT = Path(__file__).resolve().parent.parent / "report"
REPORT.mkdir(parents=True, exist_ok=True)

try:
    from docx import Document
    from docx.shared import Inches, Pt, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
except ImportError:
    print("ERROR: python-docx is required. Install with: pip install python-docx", file=sys.stderr)
    sys.exit(1)

import pandas as pd


def add_heading(doc, text, level=1):
    """Add a heading with consistent formatting."""
    heading = doc.add_heading(text, level=level)
    return heading


def add_table_from_csv(doc, csv_path, caption=None):
    """Add a formatted table from a CSV file."""
    if not csv_path.exists():
        doc.add_paragraph(f"[Data not available: {csv_path.name}]")
        return

    df = pd.read_csv(csv_path)

    if caption:
        p = doc.add_paragraph(caption)
        p.style = "Caption" if "Caption" in [s.name for s in doc.styles] else None

    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = "Light Grid Accent 1"

    # Header row
    for i, col in enumerate(df.columns):
        table.rows[0].cells[i].text = str(col)

    # Data rows
    for _, row in df.iterrows():
        cells = table.add_row().cells
        for i, val in enumerate(row):
            if isinstance(val, float):
                cells[i].text = f"{val:.4f}"
            else:
                cells[i].text = str(val)


def add_image(doc, img_path, width=Inches(5.5), caption=None):
    """Add an image with optional caption."""
    if not img_path.exists():
        doc.add_paragraph(f"[Image not available: {img_path.name}]")
        return

    doc.add_picture(str(img_path), width=width)
    if caption:
        p = doc.add_paragraph(caption)
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER


def main():
    parser = argparse.ArgumentParser(description="Generate credit risk report")
    parser.add_argument("--output", default=str(REPORT / "credit_risk_report.docx"))
    args = parser.parse_args()

    doc = Document()

    # Title
    title = doc.add_heading("Credit Risk Assessment Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(
        "Generated by the Credit Underwriting Workflow skill. "
        "All metrics computed deterministically from held-out test data."
    )

    # Section 1: Accuracy
    add_heading(doc, "1. Model Accuracy", level=1)
    doc.add_paragraph(
        "Performance metrics for classical ML models on the held-out test set. "
        "Higher AUC and KS indicate better discrimination; lower Brier and ECE "
        "indicate better calibration."
    )
    add_table_from_csv(doc, RESULTS / "accuracy.csv", "Table 1: Accuracy Metrics")
    add_image(doc, RESULTS / "roc_curves.png", caption="Figure 1: ROC Curves")

    # Section 2: SHAP Interpretability
    add_heading(doc, "2. Feature Importance (SHAP)", level=1)
    doc.add_paragraph(
        "SHAP values measure each feature's contribution to individual predictions. "
        "Summary plots show the distribution of feature impacts across test samples."
    )
    for model in ["logistic_regression", "xgboost", "mlp"]:
        img = RESULTS / f"shap_summary_{model}.png"
        if img.exists():
            add_image(doc, img, caption=f"Figure: SHAP Summary — {model.replace('_', ' ').title()}")

    if (RESULTS / "shap_stability.csv").exists():
        add_table_from_csv(doc, RESULTS / "shap_stability.csv", "Table 2: SHAP Rank Stability (Bootstrap)")

    # Section 3: Fairness
    add_heading(doc, "3. Fairness Audit", level=1)
    doc.add_paragraph(
        "Disparate impact ratios measure whether approval rates are equitable "
        "across protected groups. The four-fifths rule (DI ≥ 0.80) is the "
        "regulatory screening threshold."
    )
    add_table_from_csv(doc, RESULTS / "disparate_impact.csv", "Table 3: Disparate Impact Ratios")
    add_image(doc, RESULTS / "disparate_impact.png", caption="Figure: Disparate Impact Analysis")

    # Section 4: Drift
    add_heading(doc, "4. Temporal Drift", level=1)
    doc.add_paragraph(
        "Model performance over time, trained on historical data and tested "
        "on subsequent years."
    )
    add_table_from_csv(doc, RESULTS / "drift_metrics.csv", "Table 4: Drift Metrics")
    add_image(doc, RESULTS / "drift.png", caption="Figure: Performance and Approval Rate Over Time")

    # Section 5: LLM Evaluation
    add_heading(doc, "5. LLM Credit Evaluation", level=1)
    doc.add_paragraph(
        "Frontier LLM zero-shot credit decisioning on sampled borrower profiles "
        "from the test set. Compared against classical model baselines."
    )
    if (RESULTS / "llm_metrics.csv").exists():
        add_table_from_csv(doc, RESULTS / "llm_metrics.csv", "Table 5: LLM Accuracy Metrics")
    if (RESULTS / "llm_decisions.csv").exists():
        doc.add_paragraph(f"Full decisions logged in: llm_decisions.csv")

    # Save
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))
    print(f"Report saved: {out_path}")


if __name__ == "__main__":
    main()
